version: '3.7'

services:
  db:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my-weak-password
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nestjs.container_name
      PGADMIN_DEFAULT_PASSWORD: my-weak-password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:8080'
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
